/** Registry of audio assets (relative requires for Metro reliability). */
export type SfxName = 'tap' | 'seed' | 'capture' | 'turn' | 'win';

export const sfxSources: Record<SfxName, number> = {
  tap: require('../../../assets/audio/tap.wav'),
  seed: require('../../../assets/audio/seed.wav'),
  capture: require('../../../assets/audio/capture.wav'),
  turn: require('../../../assets/audio/turn.wav'),
  win: require('../../../assets/audio/win.wav'),
};

/**
 * Background music — a warm, lively, premium Raga Mohanam loop: a beat-driven
 * bass pulse + eighth-note pentatonic arpeggio, a singable melody, a soft
 * tanpura-like drone, and light off-beat hand percussion. Seamlessly looped via
 * an equal-power crossfade (no dip at the loop point). Generated by
 * scripts/make-ambient-melody.mjs — energetic and charming, suited to a
 * traditional board game.
 */
export const ambientSource: number = require('../../../assets/audio/ambient-melody.wav');
